[package]
name = "pool-db"
version.workspace = true
edition.workspace = true

[dependencies]
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2 = "0.10"
tracing.workspace = true
thiserror.workspace = true
chrono.workspace = true
sqlx.workspace = true

[dev-dependencies]
serde_json.workspace = true
tempfile = "3"
